### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by ogaston**

### CODE REVIEW

**Review by keywordnew — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
I'm not sure we need to update or include the dates anymore.

**Comment by WaleedAshraf** [comment]
@mhdawson because of the merge?

**Comment by MylesBorins** [comment]
@WaleedAshraf https://github.com/nodejs/TSC/issues/195#issuecomment-374443984

> The Board Foundation Subcommittee met last month and the board discussed this issue in our last meeting. Here's the summary of the discussion. The net of the conversation is that the copyright notice is not critical but the best practices were boiled down to the following:
> 
> * Do not strip or alter existing copyright notices.
> * Other projects have utilized “[Foundation Name or Project Name] and its contributors”.
> * Adding dates is not preferable. It does not have a legal impact and would be excluded only for ease of administration.
> * If a file is updated by the project past the original author, one may add the project copyright notice.
> * SPDX tagging (https://spdx.org/) can be helpful for scanning when adding new files

**Review by MylesBorins — CHANGES_REQUESTED** [review]
Based on the conversation in https://github.com/nodejs/TSC/issues/195#issuecomment-374443984 I don't think we should be changing the license header. For new license we can avoid the date... but it doesn't have legal reasons to change it

**Review by WaleedAshraf — CHANGES_REQUESTED** [review]
@ogaston Anyways, thanks for the first contribution try. 👍keep going.

**Review by keywordnew — COMMENTED** [review]
Thank you for the contribution @ogaston! 👍🏽 

Because of the legal requirements outlined in the comments above, we'll refrain from changing the license date. Future licenses will not be including a date anymore and old licenses with a date will be allowed to remain that way. 

I'll be closing this pull request without merging. Please do continue to build on your new familiarity with the Node.js project by continuing to contribute in issues and PRs! 🧡 

Glad to have you onboard!

**Pull request closed without merging**
